site_name: '&#60;dev notes/&#62;'
site_url: https://yubisel.gitlab.io
site_dir: public
theme:
  name: material
  language: en
  icon:
    logo: material/library
  favicon: images/favicon.png
  palette:
    scheme: slate
    primary: teal
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.instant #carga la pagina por xhr para comportarse como una spa
    # - navigation.expand
    - toc.integrate
    # - navigation.tabs #menu superior en tabs

nav:
  - Home: index.md
  - Programming:
    - PHP:
      - Dates: programming/php/dates.md
      - Fechas en aplicacion desde varios lugares del mundo: programming/php/global_dates.md
    - Composer: programming/composer/composer.md
    - React:
      - Newline to break (nl2br): programming/react/newline_to_break.md
    - bash:
      - bash examples: programming/bash/30_bash_examples.md
    - python:
      - rangos: programming/python/rangos.md
      - listas: programming/python/listas.md
      - tuplas: programming/python/tuplas.md
      - diccionarios: programming/python/diccionarios.md
    - html:
      - Text tags: programming/html/text_tags.md

  - Database:
    - MySql: database/mysql.md
    - SQL Server: database/sql_server.md

  - Apache:
    - General: apache/general.md
    - Permisos: apache/permits.md

  - Docker:
    - Docker:
      - notas: docker/docker_notes.md
      - install: docker/docker_install.md

  - Operating systems:
    - Linux:
      - Gnome: operating_systems/linux/gnome/extensions.md
      - Estructura de ficheros: operating_systems/linux/estructura_de_directorios.md
      - CDPATH: operating_systems/linux/cdpath.md

    - Ubuntu:
      - Clipboard: operating_systems/ubuntu/clipboard.md
      - Rename several files from console: operating_systems/ubuntu/rename_several_files_from_console.md
      - Procesos: operating_systems/ubuntu/top_process.md
      - lamp: operating_systems/ubuntu/lamp.md
      - apache: operating_systems/ubuntu/create_a_self_signed_ssl_certificate_for_apache.md
    - Windows:
      - Enable version selection in the installer: operating_systems/windows/enable_version_selection_in_the_installer.md
      - Install .NET Framework 3.5 via DISM: operating_systems/windows/install_net_framework.md
  
  - Commands/Bash programs:
    - ssh: 
      - ssh: commands/ssh/ssh.md
      - Copy the public key to server: commands/ssh/copy_the_public_key.md
    - dd: commands/dd.md
    - pwgen: commands/pwgen.md
    - seq: commands/seq.md
    - ncdu: commands/ncdu.md
    - grep: commands/grep/directory_word_search.md
    - jq: commands/jq.md
    - mktemp: commands/mktemp.md
    - tar: commands/tar.md
    - commands/uniq.md
    - others: commands/others.md

  - ToDo:
    - Films to watch: todo/films_to_watch.md

  - Links:
    - Images: links/images.md
    - Others: links/others.md
    - api: links/api.md

  - Help:
    - MkDocs: about/mkdocs.md
    - About:  about/about.md

markdown_extensions:
  - toc:
      toc_depth: 2
  - meta
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yubisel/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Yubisel
      name: GitHub

repo_name: yubisel.gitlab.io
repo_url: https://gitlab.com/yubisel/mkdocs
copyright: Copyright &copy; 2021 Ing. Yubisel Vega Alvarez
