site_name: '&#60;dev notes/&#62;'
site_url: https://yubisel.gitlab.io
site_dir: public
theme:
  name: material
  language: en
  icon:
    logo: material/library
  favicon: images/favicon.png
  palette:
    scheme: slate
    primary: teal
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.instant #carga la pagina por xhr para comportarse como una spa
    - navigation.expand
    # - toc.integrate
    # - navigation.tabs #menu superior en tabs

nav:
  - Inicio: index.md
  # - Administraci&oacute;n:
  #   - Seguridad: security.md
  #   - Salvas del sistema: backups.md
  # - Gesti&oacute;n:
  #   - Configuraci&oacute;n: configuration.md
  #   - Codificadores: codecs.md
  #   - Compras de activos: aftbuys.md
  #   - Activos: aft.md
  #   - Exportar al Versat: export.md
  #   - Depreciaci&oacute;n: reparation.md
  #   - Fecha del sistema: sistemdate.md
  - Ayuda:
    - Autores: about/authors.md
    - Sobre:  about/about.md

markdown_extensions:
  - toc:
      toc_depth: 0
  - meta
extra:
  social:
      # social icons
      # – fontawesome/brands/behance
      # – fontawesome/brands/docker
      # – fontawesome/brands/github
      # – fontawesome/brands/instagram
      # – fontawesome/brands/linkedin
      # – fontawesome/brands/medium
      # – fontawesome/brands/pied-piper-alt
      # – fontawesome/brands/product-hunt
      # – fontawesome/brands/slack
      # – fontawesome/brands/twitter
      # - fontawesome/solid/paper-plane
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yubisel/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Yubisel
      name: GitHub

repo_name: yubisel.gitlab.io
repo_url: https://gitlab.com/yubisel/mkdocs
copyright: Copyright &copy; 2021 Ing. Yubisel Vega Alvarez